name: Deploy staging

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  deployments: write
  packages: read

concurrency:
  group: staging
  cancel-in-progress: false

jobs:
  build:
    uses: LasVegasForTransit/repository-tooling/.github/workflows/release-build.yml@3567f0cb1345e8756eb5d84e0a3ea7b62695125a
    with:
      app-directory: apps/deploy
      artifact-prefix: app-release
    secrets: inherit
  attest:
    needs: build
    permissions:
      contents: read
      actions: read
      packages: read
      attestations: write
      id-token: write
    uses: LasVegasForTransit/repository-tooling/.github/workflows/release-attest.yml@3567f0cb1345e8756eb5d84e0a3ea7b62695125a
    with:
      artifact-prefix: app-release

  staging:
    needs: [build, attest]
    uses: LasVegasForTransit/repository-tooling/.github/workflows/release-publish.yml@3567f0cb1345e8756eb5d84e0a3ea7b62695125a
    with:
      target: preview
      attestation-prefix: attestation-app-release
      release-id: ${{ github.run_id }}
      commit: ${{ github.sha }}
      artifact-prefix: app-release
      app-directory: apps/deploy
      acceptance-directory: apps/app
      url: ${{ vars.LVBT_PREVIEW_URL }}
      smoke-script: worker:smoke
      browser-script: worker:test:browser
    secrets: inherit
